#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pymongo
Version  : 4.0.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/3f/ff/7ec17064d403799d644f7db9c2e99202441849aebe771efe3199f3dd9076/pymongo-4.0.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/3f/ff/7ec17064d403799d644f7db9c2e99202441849aebe771efe3199f3dd9076/pymongo-4.0.1.tar.gz
Summary  : Python driver for MongoDB <http://www.mongodb.org>
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-pymongo-license = %{version}-%{release}
Requires: pypi-pymongo-python = %{version}-%{release}
Requires: pypi-pymongo-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
=======
PyMongo
=======
:Info: See `the mongo site <http://www.mongodb.org>`_ for more information. See `GitHub <http://github.com/mongodb/mongo-python-driver>`_ for the latest source.
:Documentation: Available at `pymongo.readthedocs.io <https://pymongo.readthedocs.io/en/stable/>`_
:Author: The MongoDB Python Team

%package license
Summary: license components for the pypi-pymongo package.
Group: Default

%description license
license components for the pypi-pymongo package.


%package python
Summary: python components for the pypi-pymongo package.
Group: Default
Requires: pypi-pymongo-python3 = %{version}-%{release}

%description python
python components for the pypi-pymongo package.


%package python3
Summary: python3 components for the pypi-pymongo package.
Group: Default
Requires: python3-core
Provides: pypi(pymongo)

%description python3
python3 components for the pypi-pymongo package.


%prep
%setup -q -n pymongo-4.0.1
cd %{_builddir}/pymongo-4.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1646324856
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pymongo
cp %{_builddir}/pymongo-4.0.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pymongo/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pymongo/7df059597099bb7dcf25d2a9aedfaf4465f72d8d

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
